### ISSUE TITLE
searching causes an unknown error (flatpak)

### ISSUE THREAD

**Issue by revulent** [Vysp3r/RetroPlus#30] opened 2024-02-19 04:22 UTC
**Describe the bug**
searching for anything leads to an unknown error

**To Reproduce**
1. type a string in the search bar and hit enter

**Expected behavior**
a search

**Screenshots**

![image](https://github.com/Vysp3r/RetroPlus/assets/49258216/f93aa7a5-8840-45f3-a12f-f14d7238b8c5)

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora 36]
 fedora 39
 - DE: [e.g. GNOME 42]
 kde plasma
 - Type: [Source or Flathub]
 flathub

**Comment by Vysp3r** [comment] 2024-02-19 12:11
Closing since it's a duplicate of https://github.com/Vysp3r/RetroPlus/issues/24. Follow the issue I linked to follow the progress of your issue.

**Closed by Vysp3r** 2024-02-19 12:11 UTC
Labels: bug, duplicate
